language: java

jdk:
  - oraclejdk10

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/Bureau/MGL/Unit\ testing/gradle/

script:
  - ./gradlew test

before_install:
 - chmod +x gradlew